products/urls.py
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    path('', views.index, name='index'),
    path('gift/<category>', views.categorydetail, name='category'),
    path('gift/<category>/<rank>', views.productdetail, name='product'),
    path('add/new', views.addProduct, name='addproduct'),
    
]

thegiftrank/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('products.urls')),
    path('admin/', admin.site.urls),
]

products/models.py
from django.db import models
import random

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=500)
    short_name = models.CharField(max_length=500)
    description = models.CharField(max_length=500)
    short_description = models.CharField(max_length=500)
    img_thumb = models.CharField(max_length=500)
    img_full = models.CharField(max_length=500)
    rank = models.IntegerField()
    mycategory = models.CharField(max_length=500)
    realcategory = models.CharField(max_length=500)
    subcategory = models.CharField(max_length=500)
    date = models.DateField(auto_now=True)
    pageviews = models.IntegerField(default=random.randint(1, 275))   
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)
    video = models.CharField(max_length=500)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return self.short_name

class Store(models.Model):
    name = models.CharField(max_length=500)
    rating = models.IntegerField(default=0)
    homepage = models.CharField(max_length=500)
    reflink = models.CharField(max_length=500)

    def __str__(self):
        return self.name

class PriceLink(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="link")
    store = models.ForeignKey(Store, on_delete=models.CASCADE, related_name="store")
    price = models.IntegerField()
    clicks = models.IntegerField()
    url = models.CharField(max_length=500)

    def __str__(self):
        return f"{self.product} : {self.store} : {self.price}"

products/views.py
from django.shortcuts import render
from django.http.response import HttpResponse
from .models import Product, PriceLink, Store


def index(request):
    all_products = Product.objects.all().order_by('-pageviews')[:4]
    context = {'all_products': all_products}
    return render(request, 'products/index.html', context)


def categorydetail(request, category):
    clickeditems = Product.objects.all().order_by('-pageviews')[:10]
    all_products = Product.objects.filter(mycategory=category)
    if all_products:
        all_products = all_products
    else:
        all_products = Product.objects.filter(realcategory=category)
        if all_products:
            all_products = all_products
        else:
            all_products = Product.objects.filter(subcategory=category)
    subcategories = {}
    for product in all_products:
        if product.mycategory not in subcategories:
            subcategories.update({product.mycategory: 1})
        else:
            subcategories[product.mycategory] += 1
        if product.subcategory not in subcategories:
            subcategories.update({product.subcategory: 1})
        else:
            subcategories[product.subcategory] += 1
        if product.realcategory not in subcategories:
            subcategories.update({product.realcategory: 1})
        else:
            subcategories[product.realcategory] += 1
    context = {'all_products': all_products,
               'subcategories': sorted(subcategories.items(), key=lambda item: item[1], reverse=True), 'clickeditems': clickeditems, 'MAINCATEGORY': category}
    return render(request, 'products/listallproducts.html', context)


def productdetail(request, rank, category):
    product = Product.objects.get(rank=rank, mycategory=category)
    relatedproducts =  Product.objects.filter(subcategory=product.subcategory)[:4]
    pricelinks = product.link.all()
    context = {'product': product, 'pricelinks': pricelinks, 'relatedproducts': relatedproducts}
    return render(request, 'products/oneproduct.html', context)


def addProduct(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        name = request.POST['name']
        short_name = request.POST['short_name']
        description = request.POST['description']
        short_description = request.POST['short_description']
        img_thumb = request.POST['img_thumb']
        img_full = request.POST['img_full']
        rank = request.POST['rank']
        mycategory = request.POST['mycategory']
        realcategory = request.POST['realcategory']
        subcategory = request.POST['subcategory']
        price = request.POST['price']
        url = request.POST['url']
        # check whether it's valid:
        full = Product(
            name=name,
            short_name=short_name,
            description=description,
            short_description=short_description,
            img_thumb=img_thumb,
            img_full=img_full,
            rank=rank,
            mycategory=mycategory,
            realcategory=realcategory,
            subcategory=subcategory
        )
        full.save()
        STORE = Store.objects.get(name="Amazon")
        sendpricelink = PriceLink(
        product=full,
        store=STORE,
        price=price,
        clicks=0,
        url=url
        )
        sendpricelink.save()
        return HttpResponse(f"{full}: {sendpricelink}")
        

    # if a GET (or any other method) we'll create a blank form
    else:
        return HttpResponse('Something Went wrong')

products/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>The Gift Rank</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Acme&display=swap" rel="stylesheet">
    {% load static %}
    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'products/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'products/cover.css' %}">
    <script src="https://kit.fontawesome.com/8ab976f915.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
</head>

<body>
    <div class="container-fluid fullme">
        <div class="container-fluid d-flex justify-content-center redback fullme">
            <nav class="navbar navbar-custom navbar-expand-lg fullme">

                <a class="navbar-brand" href="#">
                    <img src="http://thegiftrank.com/css/logo.png" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
                    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="../"><strong>Home</strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'products:category' 'electronics' %}"><strong>Electrical</strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'products:category' 'drugstore' %}"><strong>Health</strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'products:category' 'beauty' %}"><strong>Beauty</strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'products:category' 'kids' %}"><strong>Toys</strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'products:category' 'electronics' %}"><strong>Most Clicked</strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'products:category' 'electronics' %}"><strong>Most Viewed</strong></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        </header>
        
        <main role="main" class="container-fluid">
            {% block content %}
            {% endblock %}
        </main>
        

        <footer class="myfoot container-fluid">
            <div class="inner">
                <p><a href="https://thegiftrank.com">The Gift Rank</a>, made by <a href="#">pkweb</a>.</p>
            </div>
        </footer>
    </div>
</body>

</html>

products/templates/products/index.html
{% extends "base.html" %}
{% block content %}
<div class="coverback curvedborder">
    <div class="container">
    <h1 class="text-danger maintitle">Need A Gift?</h1>
    <p class="fullopac h5 text-black">We have collected the most gifted presents bought on the internet,
        found the
        cheapest
        price, and then listed them all here.</p>
    <p class="fullopac h5 text-black">Have a browse and find some inspiration for your next present.</p>
    <div class="row buton">
        <div class="col-md-6 col-sm-12">
            <a href="#" class="btn btn-lg btn-block btn-secondary">Most Viewed</a>
        </div>
        <div class="col-md-6 col-sm-12">
            <a href="#" class="btn btn-lg btn-block btn-outline-secondary">Most Clicked</a>
        </div>
    </div>
</div>
</div>


<div class="topranked container-fluid">
    <div class="bg-white container-fluid hhead curvedborder">
        <h2 class="text-danger">Check out the most gifted items on the internet at the moment</h2>
    </div>
    <div class="card-deck" id="products">
        {% if all_products %}
        {% for product in all_products %}
        <div class="card">
            <div class="card-header myCapital">
                #{{ product.rank }} in {{ product.mycategory }}
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-3 col-sm-12">
                        <img src="{{ product.img_thumb }}" class="card-imgtg"
                            alt="{{ product.short_name }}">
                    </div>
                    <div class="col-md-9 col-sm-12">
                        <h6 class="card-title">{{ product.short_name }}</h6>
                        <p>Views: {{ product.pageviews }}</p>
                        <p><i class="fas fa-laugh fa-3x"></i> {{ product.likes }} <i class="fas fa-frown fa-3x"></i> {{ product.dislikes }}</p>
                        <small class="text-muted">Updated on {{ product.date }}</small>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <a href="{% url 'products:product' product.mycategory product.rank %}"
                    class="btn btn-lg btn-block btn-secondary myCapital">See Prices</a>
                <a href="{% url 'products:category' product.mycategory %}"
                    class="btn btn-block btn-outline-secondary myCapital">All 
                    {{ product.mycategory|capfirst }} Products</a>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <p>No polls are available.</p>
        {% endif %}
    </div>

</div>
{% endblock %}

products/templates/products/listallproducts.html
{% extends "base.html" %}
{% block content %}
<div class="row no-gutters">
    <div class="col-9">
        {% if all_products %}
        <div class="container-fluid">
            {% for product in all_products %}
            <div class="row">
                <div class="card">
                    <div class="card-header myCapital">
                        <p class="float-left">#{{ product.rank }} in {{ product.mycategory }}</p>
                        <p class="float-right">Tags: {{ product.realcategory }}, {{ product.subcategory }} </p>
                    </div>
                    <div class="card-body">
                        <div class="row no-gutters">
                            <div class="col-md-2 imgdiv">
                                <img src="{{ product.img_thumb }}" class="card-img imgimg"
                                    alt="{{ product.short_name }}">
                            </div>
                            <div class="col-md-10">
                                <div class="row">
                                    <div class="col-6">
                                        <h5 class="card-title">{{ product.short_name|upper }}</h5>
                                        <p class="card-text">{{ product.short_description }}</p>
                                        <p class="card-text"><small class="text-muted">Updated on {{ product.date }}</small>
                                        </p>
                                    </div>
                                    <div class="col-6">
                                        <div class="row text-center">
                                            <div class="col-6">
                                                <p><i class="fas fa-laugh fa-3x"></i> {{ product.likes }}</p>
                                            </div>
                                            <div class="col-6">
                                                <p><i class="fas fa-frown fa-3x"></i> {{ product.dislikes }}</p>
                                            </div>
                                        </div>
                                        <a href="{% url 'products:product' product.mycategory product.rank %}"
                                            class="btn btn-block btn-secondary myCapital">See Prices</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>
        {% else %}
        <p>No polls are available.</p>
        {% endif %}
    </div>
    <div class="col-3">
        {% if subcategories %}
        <ul class="list-group">

            <li class="list-group-item">
                <h3>Similiar Categories</h3>
            </li>
            {% for k, v in subcategories %}
            <li class="list-group-item">
                <a href="{% url 'products:category' k %}">
                    <p class="sidetext">{{ k|capfirst }}: <span class="badge badge-primary badge-pill float-right">{{ v }}</span>
                    </p>
                </a>
            </li>

            {% endfor %}

            {% else %}
            <p>No similiar categories.</p>
            {% endif %}
        </ul>
        {% if clickeditems %}
        <div class="container">
            <h3>Most Clicked Products</h3>
            <p><small class="text-muted">On all of The Gift Rank <br></small></p>
            {% for clickeditem in clickeditems %}
            <div class="row">
                <div class="col-4">
                    <img src="{{ clickeditem.img_thumb }}" alt="" height="42" width="42">
                </div>
                <div class="col-8">
                    <p><a
                            href="{% url 'products:product' clickeditem.mycategory clickeditem.rank %}">{{ clickeditem.short_name }}</a>
                    </p>

                </div>
            </div>
            {% endfor %}
            {% else %}
            <p>No similiar categories.</p>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

products/templates/products/oneproduct.html
{% extends "base.html" %}
{% block content %}
{% if product %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <!-- Area for product Image-->
            <img src="{{ product.img_thumb }}" alt="{{ product.short_name }}" class="rounded" height="250" width="250">
        </div>
        <div class="col-6">
            <!-- Area for product Details-->
            <h2>{{ product.name|truncatewords:10 }}</h2>
            <p>{{ product.description }}</p>
            <div class="row">
                <div class="col-6">
                    <p>Rating: {{ product.rating }} / 5</p>
                    <p>Product Views: {{ product.pageviews }}</p>
                </div>
                <div class="col-6">
                    <p><i class="fas fa-heart fa-3x"></i> {{ product.likes }} <i class="fas fa-heart-broken fa-3x"></i> {{ product.dislikes }}</p>
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    <p>{{ product.mycategory|capfirst }}</p>
                </div>
                <div class="col-3">
                    <p>{{ product.realcategory|capfirst }}</p>
                </div>
                <div class="col-3">
                    <p>{{ product.subcategory|capfirst }}</p>
                </div>
                <div class="col-3">
                    <p>Date Added: {{ product.date|date:"D d M Y" }}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <!-- Area for product prices-->
        {% if pricelinks %}
        <ul>
            {% for link in pricelinks %}
            <li>{{ link.store }} : {{ link.price }} : {{ link.url }}</li>
            {% endfor %}
        </ul>
        {% else %}
        <p>Product Has No Links Yet</p>
        {% endif %}
    </div>
    <div class="row">
        <!-- Are for Related Products-->
        <div class="card-deck" id="products">
            {% if all_products %}
            {% for product in relatedproducts %}
            <div class="card">
                <div class="card-header myCapital">
                    #{{ product.rank }} in {{ product.mycategory }}
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3 col-sm-12">
                            <img src="{{ product.img_thumb }}" class="card-imgtg" alt="{{ product.short_name }}">
                        </div>
                        <div class="col-md-9 col-sm-12">
                            <h6 class="card-title">{{ product.short_name }}</h6>
                            <p>Views: {{ product.pageviews }}</p>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <a href="{% url 'products:product' product.mycategory product.rank %}"
                        class="btn btn-lg btn-block btn-secondary myCapital">See Prices</a>
                    <a href="{% url 'products:category' product.mycategory %}"
                        class="btn btn-lg btn-block btn-outline-secondary myCapital">All
                        {{ product.mycategory }}'s</a>
                </div>
                <div class="card-footer">
                    <small class="text-muted float-left">Updated on {{ product.date }}</small>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p>No polls are available.</p>
            {% endif %}
        </div>
    </div>
</div>


{% else %}
<p>Product Does Not Exist</p>
{% endif %}
{% endblock %}